spring.application.name=Pablo
spring.datasource.url=jdbc:mysql://localhost:3306/certificados_blockchain

spring.datasource.username=root

spring.datasource.password=dinorey123

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true